// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbYYxONev8GP0CvtsY6ncorckAkD-zCuc',
    appId: '1:119876292918:web:44ed52aee806c0d53c6397',
    messagingSenderId: '119876292918',
    projectId: 'todo-app-7e815',
    authDomain: 'todo-app-7e815.firebaseapp.com',
    storageBucket: 'todo-app-7e815.firebasestorage.app',
    measurementId: 'G-6DL83JJ7Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC2cQxsY_u8jl0dKYi60TNZ8kdE4KL-g8',
    appId: '1:119876292918:android:fbafa9fdee18e61b3c6397',
    messagingSenderId: '119876292918',
    projectId: 'todo-app-7e815',
    storageBucket: 'todo-app-7e815.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmCeuKl1lpQ-BL8dFYp6Ka_FXC1Yi8Wvo',
    appId: '1:119876292918:ios:558ed4a79eb863bf3c6397',
    messagingSenderId: '119876292918',
    projectId: 'todo-app-7e815',
    storageBucket: 'todo-app-7e815.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmCeuKl1lpQ-BL8dFYp6Ka_FXC1Yi8Wvo',
    appId: '1:119876292918:ios:558ed4a79eb863bf3c6397',
    messagingSenderId: '119876292918',
    projectId: 'todo-app-7e815',
    storageBucket: 'todo-app-7e815.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbYYxONev8GP0CvtsY6ncorckAkD-zCuc',
    appId: '1:119876292918:web:5b65e94d066757f63c6397',
    messagingSenderId: '119876292918',
    projectId: 'todo-app-7e815',
    authDomain: 'todo-app-7e815.firebaseapp.com',
    storageBucket: 'todo-app-7e815.firebasestorage.app',
    measurementId: 'G-HSE1HWYS61',
  );
}
